### ISSUE TITLE
Баг с обнулением билетов

### ISSUE THREAD

**Issue by 00lim00** [0x-John/AutoCliker-Blum#8]
Сначала не находило кнопку, поменял на свой скрин кнопки, запустил. После указания значений написало поиск кнопки и бам - в блум 0 билетиков. Короче уже, наверное, обрабатывают автоматический захват из других источников и снимают все билеты в качестве штрафа за такие читы. Будьте осторожны и пользуйтесь на свой страх и риск

**Comment by asdxzcvbf13** [comment]
Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и  тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя оследить

**Comment by asdxzcvbf13** [comment]
> Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя оследить

Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя оследить

**Comment by asdxzcvbf13** [comment]
> Сначала не находило кнопку, поменял на свой скрин кнопки, запустил. После указания значений написало поиск кнопки и бам - в блум 0 билетиков. Короче уже, наверное, обрабатывают автоматический захват из других источников и снимают все билеты в качестве штрафа за такие читы. Будьте осторожны и пользуйтесь на свой страх и риск

Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя оследить

**Comment by 00lim00** [comment]
> > Сначала не находило кнопку, поменял на свой скрин кнопки, запустил. После указания значений написало поиск кнопки и бам - в блум 0 билетиков. Короче уже, наверное, обрабатывают автоматический захват из других источников и снимают все билеты в качестве штрафа за такие читы. Будьте осторожны и пользуйтесь на свой страх и риск
> 
> Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя отследить

Уже вернулись билеты. Наверное, был баг какой-то. Я много перезаходил и ждал, ничего не менялось, теперь всё нормально. Иногда бывает, что что-то не работает сразу, но это не повод для оскорблений и резких слов.
Извиняюсь, что поднял тему проблемы зря. Это оказался временный баг, и сейчас всё работает как надо, за что спасибо разработчику. Спасибо за понимание

**Comment by 00lim00** [comment]
> > Сначала не находило кнопку, поменял на свой скрин кнопки, запустил. После указания значений написало поиск кнопки и бам - в блум 0 билетиков. Короче уже, наверное, обрабатывают автоматический захват из других источников и снимают все билеты в качестве штрафа за такие читы. Будьте осторожны и пользуйтесь на свой страх и риск
> 
> Алеша, давай чушь не неси! Все замечательно работает в прямых руках, ничего не списали! Ты до этого использовал какой то софт который накручивал поинты и тебя забанили, теперь валишь на других. Кликер не контактирует с серверной частью, его нельзя отследить

Уже вернулись билеты. Наверное, был баг какой-то. Я много перезаходил и ждал, ничего не менялось, теперь всё нормально. Иногда бывает, что что-то не работает сразу, но это не повод для оскорблений и резких слов.
Извиняюсь, что поднял тему проблемы зря. Это оказался временный баг, и сейчас всё работает как надо, за что спасибо разработчику. Спасибо за понимание
